---
title: "Some recent talks"
output: 
  html_document:
   toc: false
   logo: images/LogoSULPSM.png
   number_sections: false
   highlight: tango
   css: style.css
   includes:
     before_body: extlogo.html
---

<br>

- [Some latent variable models in ecology](slides/StatMathAppli-Frejus-2509.pdf), StatMathAppli, Fréjus (sep'25)

- [Markov-switching (discrete-time) Hawkes process](slides/Lancaster-2506.pdf), STOR-I seminar, Lancaster University (jun'25)

- [Segmentation and classification of a Hawkes process](slides/RMR2024-2406.pdf), Rencontres Mathématiques de Rouen (Jun'24)

- [A partial history of latent variable models in genomics](slides/SMPGD-2402.pdf), Statistical Methods for Post-Genomic Data, Paris (Feb'24)


- [Change-point detection in a Poisson process](slides/MAP5-2310.pdf), Special colloquium session in tribute to Catherine Huber-Carol, Paris (Oct'23)

- [SMC sampling from deterministic approximations: Application to the Poisson stochastic block-model](slides/London-2212.pdf), CMStatistics, London (Dec'22). 

- [Tree-based mixtures: Application in epidemiology](slides/IHP-2210-BayesHS.pdf),
Bayesian Methods for the Social Sciences, Paris (Oct'22)

- [An exchangeable model for (ecological) bipartite network](slides/ESSEC-2203.pdf), ESSEC statistical seminar (Mar'22).
